config/routes.rb
Rails.application.routes.draw do

	root 'public#index'

	get 'show/:permalink', :to => 'public#show', :as => 'public_show' #to have prefix route

	get 'admin', :to => 'access#menu'
	get 'access/menu'
	get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'

	resources :admin_users, :only => [:index, :new, :create, :edit, :update, :delete, :destroy] do
		member do
			get :delete
		end
	end

	resources :subjects do
		member do
			get :delete
		end
	end
	# get 'subjects/index'
	# get 'subjects/show/:id'

	# get 'subjects/new'
	# post 'subjects/create'

	# get 'subjects/edit/:id'
	# patch 'subjects/update/:id'

	# get 'subjects/delete/:id'
	# delete 'subjects/destroy/:id'

	resources :pages do
		member do
			get :delete
		end
	end

	resources :sections do
		member do
			get :delete
		end
	end

	get 'demo/index'
	get 'demo/hello'
	get 'demo/other_hello'
	get 'demo/lynda'
	get 'demo/escape_output'

end

app/models/subject.rb
class Subject < ApplicationRecord

	acts_as_list

	has_many :pages

	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("position ASC") }
	scope :newest_first, lambda { order("created_at DESC") }
	scope :search, lambda { |query| where("name LIKE ?", "%#{query}%") }

	validates_presence_of :name
	validates_length_of :name, :maximum => 255
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_subject, :only => [:show, :edit, :update, :delete, :destroy]
  before_action :set_subject_count, :only => [:new, :create, :edit, :update]

  def index
    logger.debug("################# Testing logger.")
    @subjects = Subject.sorted
  end

  def show
  end

  def new
    @subject = Subject.new({:name => 'Default'})
  end

  def create
    # init new object wil vals
    @subject = Subject.new(subject_params)
    # save ?
    if @subject.save
      # succ
      flash[:notice] = "Subject #{@subject.name} created successfully!"
      redirect_to(subjects_path)
    else
      # fail
      flash[:error] = "Something went wrong"
      render('new')
    end
  end

  def edit
  end

  def update
    # save ?
    if @subject.update_attributes(subject_params)
      # succ
      flash[:notice] = "Subject #{@subject.name} updated!"
      redirect_to(subject_path(@subject))
    else
      # fail
      flash[:error] = "Something went wrong"
      render('edit')
    end
  end

  def delete
  end

  def destroy
    @subject.destroy
    flash[:notice] = "Subject #{@subject.name} deleted!"
    redirect_to(subjects_path)
  end

  private

  def find_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end

  def set_subject_count
    @subject_count = Subject.count
    if params[:action] == 'new' || params[:action] == 'create'
      @subject_count += 1
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
	<tr>
		<th>Name</th>
		<td><%= f.text_field(:name) %></td>
	</tr>
	<tr>
		<th>Position</th>
		<td><%= f.select(:position, 1..@subject_count) %></td>
	</tr>
	<tr>
		<th>Visible</th>
		<td><%= f.check_box(:visible) %></td>
	</tr>
	<tr>
		<th>Created at</th>
		<td><%= f.datetime_select(:created_at,:order => [:month, :day, :year]) %></td>
	</tr>
</table>

app/views/subjects/delete.html.erb
<% @page_title = "Delete subject" %>

<%= link_to("<< Back to List", subjects_path, :class => 'back-list') %>

<div class="subjects delete">
	<h2>Delete Subject</h2>
	<%= form_for(@subject, :method => 'delete') do |f| %>
		<p>Are you sure you want to permanently delete this subject?</p>
		<p class="reference-name"><%= f.object.name %></p>
		<div class="fomr-buttons">
			<%= f.submit("Delete Subject") %>
		</div>
	<% end %>
</div>

app/views/subjects/edit.html.erb
<% @page_title = "Edit subject" %>

<%= link_to("<< Back to List", subjects_path, :class => 'back_list')%>
<div class="subjects edit">
	<h2>Update Subject</h2>
	<%= form_for(@subject) do |f|%>

		<%= render(:partial => 'form', :locals => {:f => f})%>

		<div class="form-buttons">
			<%= f.submit("Update Subject") %>
		</div>
	<% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title = "All subjects" %>

<div class="subjects index">
	<%= link_to("Back to menu", admin_path, :class => 'back-link')%>
	<h2>Listing Subjects</h2>

	<%= image_tag('plus_s.png', :size => '11x11', :alt => '+') %>
	<%= link_to("Add New Subject", new_subject_path, :class => 'action new')%>
	<table class="listing" summary="Subject list">
		<tr class="header">
			<th>#</th>
			<th>Subject</th>
			<th>Visible?</th>
			<th>Pages</th>
			<th>Actions</th>
		</tr>
		<% @subjects.each do |subject|%>
		<tr>
			<td><%= subject.position %></td>
			<td><%= subject.name %></td>
			<td class="center"><%= status_tag(subject.visible) %></td>
			<td class="center"><%= subject.pages.size %></td>
			<td class="actions">
				<%= link_to("View pages", pages_path(:subject_id => subject.id), :class => 'action show') %>
				<%= link_to("Show", subject_path(subject), :class => 'action show') %>
				<%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
				<%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/subjects/new.html.erb
<% @page_title = "New subject" %>

<%= link_to("<< Back to List", subjects_path, :class => 'back_list')%>
<div class="subjects new">
	<h2>Create Subject</h2>
	<%= form_for(@subject) do |f|%>

		<%= render(:partial => 'form', :locals => {:f => f})%>

		<div class="form-buttons">
			<%= f.submit("Create Subject") %>
		</div>
	<% end %>
</div>

app/views/subjects/show.html.erb
<% @page_title = "View subject" %>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
	<h2>Show Subject</h2>

	<table summary="Subject detail view">
		<tr>
			<th>Name</th>
			<td><%= @subject.name %></td>
		</tr>
		<tr>
			<th>Position</th>
			<td><%= @subject.position %></td>
		</tr>
		<tr>
			<th>Visible?</th>
			<td><%= @subject.visible ? 'true' : ' false' %></td>
		</tr>
		<tr>
			<th>Created</th>
			<td><%= @subject.created_at %></td>
		</tr>
		<tr>
			<th>Updated</th>
			<td><%= @subject.updated_at %></td>
		</tr>
	</table>
</div>