config/routes.rb
Rails.application.routes.draw do

	root 'public#index'

	get 'show/:permalink', :to => 'public#show', :as => 'public_show' #to have prefix route

	get 'admin', :to => 'access#menu'
	get 'access/menu'
	get 'access/login'
	post 'access/attempt_login'
	get 'access/logout'

	resources :admin_users, :only => [:index, :new, :create, :edit, :update, :delete, :destroy] do
		member do
			get :delete
		end
	end

	resources :subjects do
		member do
			get :delete
		end
	end
	# get 'subjects/index'
	# get 'subjects/show/:id'

	# get 'subjects/new'
	# post 'subjects/create'

	# get 'subjects/edit/:id'
	# patch 'subjects/update/:id'

	# get 'subjects/delete/:id'
	# delete 'subjects/destroy/:id'

	resources :pages do
		member do
			get :delete
		end
	end

	resources :sections do
		member do
			get :delete
		end
	end

	get 'demo/index'
	get 'demo/hello'
	get 'demo/other_hello'
	get 'demo/lynda'
	get 'demo/escape_output'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

	FORBIDDEN_USERNAMES = ['user', 'admin', 'basic']

	#self.table_name = "admin_users"

	has_secure_password

	has_and_belongs_to_many :pages
	has_many :section_edits
	has_many :sections, :through => :section_edits

	scope :sorted, lambda { order(last_name: :asc).order(first_name: :asc) }

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates_presence_of :first_name
	validates_length_of :first_name, :maximum => 25

	validates_presence_of :last_name
	validates_length_of :last_name, :maximum => 50

	validates :username,
		:presence => true,
		:length => { :within => 8..25 },
		:uniqueness => true

	validates_presence_of :email
	validates_length_of :email, :maximum => 100
	validates_format_of :email, :with => EMAIL_REGEX
	validates_uniqueness_of :email
	validates_confirmation_of :email

	validate :username_is_allowed
	validate :no_new_users_on_mondays, :on => :create

	def full_name
		first_name + " " + last_name
	end

	private

	def username_is_allowed
		if FORBIDDEN_USERNAMES.include?(username)
			errors.add(:username, "has been restricted from use.")
		end
	end

	def no_new_users_on_mondays
		if Time.now.wday == 1
			errors.add(:base, "No new users on Mondays.")
		end
	end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

	layout 'admin'

	before_action :confirm_logged_in
	before_action :find_user, :only => [:edit, :update, :delete, :destroy]
	# before_action :set_user_count, :only => [:new, :create, :edit, :update]

	def index
		@users = AdminUser.sorted
	end

	def new
		@admin_user = AdminUser.new()
	end

	def create
		@admin_user = AdminUser.new(user_params)
		if @admin_user.save
			flash[:notice] = "Created new user"
			redirect_to(admin_users_path)
		else
			flash[:error] = "Failed to create user"
			render("new")
		end
	end

	def edit
	end

	def update
		if @admin_user.update_attributes(user_params)
			flash[:notice] = "Updated user " + @admin_user.username
			redirect_to(admin_users_path)
		else
			flash[:error] = "Failed to update user " + @admin_user.username
			render("edit")
		end
	end

	def delete
	end

	def destroy
		if @admin_user.destroy
			flash[:notice] = "Deleted user " + @admin_user.username
			redirect_to(admin_users_path)
		end
	end

	private

	def find_user
		@admin_user = AdminUser.find(params[:id])
	end

	def set_user_count
		@user_count = AdminUser.count
		if params[:action] == 'new' || params[:action] == 'create'
			@user_count += 1
		end
	end

	def user_params
		params.require(:admin_user).permit(:first_name, :last_name, :username, :email, :password)
	end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_messages_for(f.object) %>

<table style="margin: 0 auto;" summary="User form fields">
	<tr>
		<th>Username:</th>
		<td><%= f.text_field(:username) %></td>
	</tr>
	<tr>
		<th>First Name:</th>
		<td><%= f.text_field(:first_name) %></td>
	</tr>
	<tr>
		<th>Last Name:</th>
		<td><%= f.text_field(:last_name) %></td>
	</tr>
	<tr>
		<th>Email:</th>
		<td><%= f.text_field(:email) %></td>
	</tr>
	<tr>
		<th>Confirm Email:</th>
		<td><%= f.text_field(:email_confirmation) %></td>
	</tr>
	<tr>
		<th>Password:</th>
		<td><%= f.password_field(:password) %></td>
	</tr>
	<tr>
		<th>Confirm Password:</th>
		<td><%= f.password_field(:password_confirmation) %></td>
	</tr>
</table>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete user" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-list') %>

<div class="users delete">
	<h2>Delete User</h2>
	<%= form_for(@user, :method => 'delete') do |f| %>
		<p>Are you sure you want to permanently delete this user?</p>
		<p class="reference-name"><%= f.object.username %></p>
		<div class="form-buttons">
			<%= f.submit("Delete User") %>
		</div>
	<% end %>
</div>

app/views/admin_users/edit.html.erb
<% @page_title = "Edit user" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back_list')%>
<div class="users edit">
	<h2>Update User</h2>
	<%= form_for(@admin_user) do |f|%>

		<%= render(:partial => 'form', :locals => {:f => f}) %>

		<div class="form-buttons">
			<%= f.submit("Update User") %>
		</div>
	<% end %>
</div>

app/views/admin_users/index.html.erb
<% @page_title = "All users" %>

<div class="users index">
	<%= link_to("Back to menu", admin_path, :class => 'back-link')%>
	<h2>Listing Users</h2>
	<%= image_tag('plus_s.png', :size => '11x11', :alt => '+') %>
	<%= link_to("Add New User", new_admin_user_path, :class => 'action new')%>
	<table class="listing" summary="User list">
		<tr class="header">
			<th>User ID</th>
			<th>Username</th>
			<th>Full Name</th>
			<th>Emial</th>
			<th>Actions</th>
		</tr>
		<% @users.each do |user|%>
		<tr>
			<td><%= user.id %></td>
			<td><%= user.username %></td>
			<td><%= user.full_name %></td>
			<td><%= user.email %></td>
			<td class="actions">
				<%= link_to("Edit", edit_admin_user_path(user), :class => 'action edit') %>
				<%= link_to("Delete", delete_admin_user_path(user), :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "Create user" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back_list')%>
<div class="users edit">
	<h2>Create User</h2>
	<%= form_for(@admin_user) do |f|%>

		<%= render(:partial => 'form', :locals => {:f => f}) %>

		<div class="form-buttons">
			<%= f.submit("Create User") %>
		</div>
	<% end %>
</div>